FROM python:3.11-slim

WORKDIR /app

COPY backend/requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY backend/ ./

EXPOSE 9000

CMD ["fastmcp", "run", "mcp/server.py.py:mcp", "--transport", "http", "--host", "0.0.0.0", "--port", "9000", "--path", "/"]
